using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EntityModel
{
    public class PersonalInformation
    {
        public Int64 PID { get; set; }
        public string ApplicationID { get; set; }
        public string CandidateName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public string Religion { get; set; }
        public string Region { get; set; }
        public string MotherTongue { get; set; }
        public string AnnualFamilyIncome { get; set; }
        public string AadhaarNumber { get; set; }
        public string Nationality { get; set; }
        public string CAddressLine1 { get; set; }
        public string CAddressLine2 { get; set; }
        public string CAddressLine3 { get; set; }
        public string CAddress { get; set; }
        public string CState { get; set; }
        public string CDistrict { get; set; }
        public string CTaluka { get; set; }
        public string CVillage { get; set; }
        public string CPincode { get; set; }
        public string STDCode { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string EMailID { get; set; }
        public string HasBankAccount { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string CandidatureType { get; set; }
        public string FinalCandidatureType { get; set; }
        public string DocumentOf { get; set; }
        public string MothersName { get; set; }
        public string SSCDistrict { get; set; }
        public string HSCDistrict { get; set; }
        public string HSCTaluka { get; set; }
        public string HomeUniversity { get; set; }
        public string FinalHomeUniversity { get; set; }
        public string Category { get; set; }
        public string FinalCategory { get; set; }
        public string CasteNameForOpen { get; set; }
        public string AppliedForEWS { get; set; }
        public string FinalAppliedForEWS { get; set; }
        public string CasteName { get; set; }
        public string PHType { get; set; }
        public string FinalPHType { get; set; }
        public string DefenceType { get; set; }
        public string FinalDefenceType { get; set; }
        public string IsOrphan { get; set; }
        public string FinalIsOrphan { get; set; }
        public string OrphanRegistrationNo { get; set; }
        public string OrphanHasRelative { get; set; }
        public string AppliedForMinoritySeats { get; set; }
        public string LinguisticMinorityDetails { get; set; }
        public string FinalLinguisticMinorityDetails { get; set; }
        public string ReligiousMinorityDetails { get; set; }
        public string FinalReligiousMinorityDetails { get; set; }
        public string SSCBoard { get; set; }
        public string SSCPassingYear { get; set; }
        public string SSCSeatNo { get; set; }
        public decimal SSCMathMarksObtained { get; set; }
        public decimal SSCMathMarksOutOf { get; set; }
        public decimal SSCMathPercentage { get; set; }
        public decimal SSCScienceMarksObtained { get; set; }
        public decimal SSCScienceMarksOutOf { get; set; }
        public decimal SSCSciencePercentage { get; set; }
        public decimal SSCEnglishMarksObtained { get; set; }
        public decimal SSCEnglishMarksOutOf { get; set; }
        public decimal SSCEnglishPercentage { get; set; }
        public decimal SSCTotalMarksObtained { get; set; }
        public decimal SSCTotalMarksOutOf { get; set; }
        public decimal SSCTotalPercentage { get; set; }
        public string QualifyingExam { get; set; }
        public string QualifyingExamPlace { get; set; }
        public string HSCBoard { get; set; }
        public string HSCPassingYear { get; set; }
        public string HSCSeatNo { get; set; }
        public string HSCPassingStatus { get; set; }
        public decimal HSCPhysicsMarksObtained { get; set; }
        public decimal HSCPhysicsMarksOutOf { get; set; }
        public decimal HSCPhysicsPercentage { get; set; }
        public decimal HSCChemistryMarksObtained { get; set; }
        public decimal HSCChemistryMarksOutOf { get; set; }
        public decimal HSCChemistryPercentage { get; set; }
        public decimal HSCMathMarksObtained { get; set; }
        public decimal HSCMathMarksOutOf { get; set; }
        public decimal HSCMathPercentage { get; set; }
        public string HSCSubject { get; set; }
        public decimal HSCSubjectMarksObtained { get; set; }
        public decimal HSCSubjectMarksOutOf { get; set; }
        public decimal HSCSubjectPercentage { get; set; }
        public decimal HSCEnglishMarksObtained { get; set; }
        public decimal HSCEnglishMarksOutOf { get; set; }
        public decimal HSCEnglishPercentage { get; set; }
        public decimal HSCTotalMarksObtained { get; set; }
        public decimal HSCTotalMarksOutOf { get; set; }
        public decimal HSCTotalPercentage { get; set; }
        public decimal HSCPCMPercentage { get; set; }
        public decimal HSCPMSPercentage { get; set; }
        public string DiplomaMarksType { get; set; }
        public string AppearedForJEE { get; set; }
        public string JEERollNo { get; set; }
        public decimal JEEPhysicsScore { get; set; }
        public decimal JEEChemistryScore { get; set; }
        public decimal JEEMathScore { get; set; }
        public decimal JEETotalScore { get; set; }
        public string JEEPassingMonthYear { get; set; }
        public Int32 CETApplicationFee { get; set; }
        public Int32 OnlineApplicationFee { get; set; }
        public Int32 VersionNo { get; set; }
        public DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedByIPAddress { get; set; }
        public string HSCPlace { get; set; }
        public decimal HSCBioTechnologyMarksObtained { get; set; }
        public decimal HSCBioTechnologyMarksOutOf { get; set; }
        public decimal HSCBioTechnologyPercentage { get; set; }
        public decimal HSCPCSPercentage { get; set; }
        public string AppearedForDiploma { get; set; }
        public decimal DiplomaTotalMarksObtained { get; set; }
        public decimal DiplomaTotalMarksOutOf { get; set; }
        public decimal DiplomaTotalPercentage { get; set; }
        public string AppearedForNEET { get; set; }
        public Int64 NEETRollNo { get; set; }
        public decimal NEETPhysicsScore { get; set; }
        public decimal NEETChemistryScore { get; set; }
        public decimal NEETBiologyScore { get; set; }
        public decimal NEETTotalScore { get; set; }
        public string NameAsPerHSCResult { get; set; }
        public string AppliedForTFWS { get; set; }
        public string FinalAppliedForTFWS { get; set; }
        public Int64 CETApplicationFormNo { get; set; }
        //**Add Sharad CETDetails For DET New Change
        public string CETRollNo { get; set; }
        public string CETCandidateName { get; set; }
        public string CETPhysicsMarks { get; set; }
        public string CETChemistryMarks { get; set; }
        public string CETMathMarks { get; set; }
        public string CETBiologyMarks { get; set; }
        public string CETPCMTotalMarks { get; set; }
        public string CETPCBTotalMarks { get; set; }
        public string CETPCMBMAX { get; set; }
        public string NEETCName { get; set; }
        public string Comments { get; set; }
        public string HSCVillage { get; set; }
        public string FCRApplicationID { get; set; }
        public string DisplayFinalCategory { get; set; }
        public string DisplayFinalAppliedForEWS { get; set; }
    }
}
