using EntityModel;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web;

namespace BusinessLayer
{
    public interface IBusinessService
    {
        DataSet getMasterSecurityQuestion();
        DataSet getMasterGender();
        DataSet getMasterReligion();
        DataSet getMasterRegionType();
        DataSet getMasterMotherTongue();
        DataSet getMasterAnnualFamilyIncome();
        DataSet getMasterNationality();
        DataSet getMasterState();
        DataSet getMasterDistrictForState(Int32 StateID);
        DataSet getMasterTalukaForDistrict(Int32 DistrictID);
        DataSet getMasterVillageForTaluka(Int32 TalukaID);
        DataSet getMasterCandidatureType();
        DataSet getMasterDocumentForTypeA();
        DataSet getMasterDocumentOf();
        DataSet getMasterMHDistrict();
        DataSet getMasterMHTalukaForMHDistrict(Int32 DistrictID);
        DataSet getMasterCategory();
        DataSet getMasterCasteForCategory(Int16 CategoryID);
        DataSet getMasterCasteForOpenCategory(string Flag);
        DataSet getMasterPHType();
        DataSet getMasterCourse();
        DataSet getMasterDefenceType();
        DataSet getMasterMinority(string Flag);
        DataSet getMasterBoard();
        DataSet getMasterHSCSubject(Int16 HSCBoardID);
        DataSet getMasterAFC();
        DataSet getMasterWebSite();
        DataSet getMasterBank();
        DataSet getMasterLanguage();
        DataSet getMasterApplicationBlockStatus();
        DataSet getMasterUniversity(Int32 CAPRound);
        DataSet getMasterCourseStatus1(Int32 CAPRound);
        DataSet getMasterCourseStatus2(Int32 CAPRound);
        DataSet getMasterCourseStatus3(Int32 CAPRound);
        DataSet getMasterChoiceCodeStatus(Int32 CAPRound);
        DataSet getMasterDistrictForUniversity(Int32 CAPRound, Int16 UniversityID);
        DataSet getMasterARC();
        DataSet getMasterCandidateInstituteMinorityMapping();
        Int32 getApplicationStatus(string ApplicationName);

        string forgotApplicationID(string CandidateName, string FatherName, string MotherName, DateTime DOB);
        Int64 checkCandidateSecurityQuestionDetails(string ApplicationID, Int16 SecurityQuestionID, string SecurityAnswer);
        bool resetCandidatePassword(Int64 PID, string CandidatePassword, string PasswordResetBy, string PasswordResetByIPAddress);
        Int64 checkCandidateApplicationIDAndDOB(string ApplicationID, DateTime DOB);
        string verifyCandidateMobileNo(Int64 PID);
        bool sendCandidateOTPCodeForResetPassword(Int64 PID);
        bool verifyCandidateOTPCode(Int64 PID, string OTPCode);
        string verifyCandidateEMailID(Int64 PID);
        bool sendCandidateEMailVerificationCodeForResetPassword(Int64 PID, string EMailVerificationCode);
        bool verifyCandidateEMailVerificationCode(Int64 PID, string EMailVerificationCode);

        string checkOthersSecurityQuestionDetails(string LoginID, Int16 SecurityQuestionID, string SecurityAnswer);
        bool resetOthersPassword(string LoginID, string Password, string PasswordResetByIPAddress);
        string checkOthersLoginIDAndDOB(string LoginID, DateTime DOB);
        string verifyOthersMobileNo(string LoginID);
        bool sendOthersOTPCodeForResetPassword(string LoginID);
        bool verifyOthersOTPCode(string LoginID, string OTPCode);
        string verifyOthersEMailID(string LoginID);
        bool sendOthersEMailVerificationCodeForResetPassword(string LoginID, string EMailVerificationCode);
        bool verifyOthersEMailVerificationCode(string LoginID, string EMailVerificationCode);

        DataSet checkCETDetails(Int64 CETApplicationFormNo, string CETRollNo, string DOB);
        RegistrationDetails getRegistrationDetails(Int64 PID);
        string saveRegistrationDetails(RegistrationDetails obj, string CandidatePassword, Int16 SecurityQuestionID, string SecurityAnswer, Int64 CETApplicationFormNo, string OTP, string IsActive, string ModifiedBy, string ModifiedByIPAddress, string FCRApplicationID, string FCRCandidateName, string FCRCandidatureTypeName, string FCRMotherName, string FCRGender, DateTime FCRDOB);
        bool updateRegistrationDetails(RegistrationDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        Int16 getCandidatureTypeID(Int64 PID);
        bool saveCandidatureTypeDetails(Int64 PID, Int16 CandidatureTypeID, string ModifiedBy, string ModifiedByIPAddress);
        HomeUniversityAndCategoryDetails getHomeUniversityAndCategoryDetails(Int64 PID);
        bool saveHomeUniversityAndCategoryDetails(HomeUniversityAndCategoryDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        SpecialReservationDetails getSpecialReservationDetails(Int64 PID);
        bool saveSpecialReservationDetails(SpecialReservationDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        QualificationDetails getQualificationDetails(Int64 PID);
        bool saveQualificationDetails(QualificationDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        NEETDetails getNEETDetails(Int64 PID);
        bool saveNEETDetails(NEETDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        DataSet checkNEETDetailsOnSave(NEETDetails obj);
        DataSet checkNEETDetails(Int64 PID, Int64 NEETRollNo, string AppearedForNEET);
        bool saveScannedImagesStepID(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool savePayApplicationFeeStepID(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        PersonalInformation getPersonalInformation(Int64 PID);
        DataSet getSecurityQuestionDetails(Int64 PID);
        bool saveSecurityQuestionDetails(Int64 PID, Int16 SecurityQuestionID, string SecurityAnswer, string ModifiedBy, string ModifiedByIPAddress);
        bool saveFeedback(Int64 PID, string Feedback, string CreatedBy, string CreatedByIPAddress);

        bool editRegistrationDetails(RegistrationDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        bool editCandidatureTypeDetails(Int64 PID, Int16 CandidatureTypeID, HomeUniversityAndCategoryDetails objHUC, SpecialReservationDetails objSR, string ModifiedBy, string ModifiedByIPAddress);
        bool editCandidatureTypeDetailsForARC(Int64 PID, Int16 CandidatureTypeID, string ModifiedBy, string ModifiedByIPAddress);
        bool editHomeUniversityAndCategoryDetails(HomeUniversityAndCategoryDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        bool editSpecialReservationDetails(SpecialReservationDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        bool editQualificationDetails(QualificationDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        bool editNEETDetails(NEETDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        bool editCategoryDetails(Int64 PID, Int16 CategoryID, string ModifiedBy, string ModifiedByIPAddress);

        Int16 getStepIDApplicationRound(Int64 PID);
        SessionData getSessionDataForCandidate(Int64 PID);
        Int16 getAnnualFamilyIncomeID(Int64 PID);

        string getNationality(Int64 PID);
        Int16 getCategoryID(Int64 PID);
        Int16 getPHTypeID(Int64 PID);
        DataSet getDocumentList(Int64 PID);
        bool saveLogOutDateTime(Int64 SessionID);
        char getApplicationFormStatusApplicationRound(Int64 PID);
        Int32 getApplicationFeeToBePaid(Int64 PID);
        DataSet getCETDetails(Int64 CETApplicationFormNo);
        DataSet Get_MSNEETDetails(Int64 CETApplicationFormNo);
        Int32 getApplicationFeePaidAmount(Int64 PID);
        Int64 getCETApplicationFormNo(Int64 PID);
        string getMotherTongue(Int64 PID);
        string getReligion(Int64 PID);
        DataSet getRequiredDocumentsUploadStatusReportForCandidate(Int64 PID);
        DataSet getCurrentAllotmentDetails(Int64 PID);
        DataSet getCurrentAdmissionDetails(Int64 PID);
        bool isCandidateNameAppearedInFinalMeritList(Int64 PID);
        DataSet getResult(Int64 CETApplicationFormNo);
        DataSet getCurrentLink(Int64 PID, string URL);
        DataSet getEligibilityFlag(Int64 PID);
        Int32 getProposedApplicationFeeToBePaid(Int64 PID, Int32 IsCandidatureTypeChanged, Int32 IsCategoryChanged, Int32 IsPHTypeChanged, Int32 IsEWSChanged);
        DataSet getProvisionalMeritStatus(string ApplicationID, DateTime DOB);
        DataSet getFinalMeritStatus(string ApplicationID, DateTime DOB);
        bool verifyOTP(string ApplicationID, string OneTimePassword, int OTPType);
        DataSet getOTPDetails(string ApplicationID, string OneTimePassword);
        bool isApplicationFormConfirmedUsingThisMobileNo(string MobileNo);
        DataSet getSMSContent(Int64 PID, string Flag);
        bool saveOTPForMobileNoChange(Int64 PID, string OTP);
        bool verifyOTPForMobileNoChange(Int64 PID, string OTP, string MobileNo, string IpAddress, string UserLoginID);
        string getMobileNo(Int64 PID);
        bool isApplicationFormEligibleForEditting(Int64 PID);
        string isCandidateEligibleForEdittingAtARC(Int64 PID);

        DataSet getAdminNonRepliedMessages(string Flag);
        DataSet getAdminRepliedMessages(string Flag);
        DataSet getAdminSentMessages(string Flag);
        DataSet getMessagesList(string From);
        bool replyMessage(Int64 MessageID, string RepliedMessage, string RepliedBy, string RepliedByIPAddress, string RepliedTo, string IsStarMarked);
        bool adminComposeMessage(string To, string From, string Message, string FilePath1, string FilePath2, string SentBy, string SentByIPAddress);
        DataSet getAFCNonRepliedMessages(string AFCCode);
        DataSet getAFCBroadcastedMessages(string AFCCode);
        DataSet getAFCRepliedMessages(string AFCCode);
        bool afcComposeMessage(string To, string From, string Subject, string Message, string FilePath1, string FilePath2, string SentBy, string SentByIPAddress);
        DataSet adminComposeSMS(string To, string From, string Message, string SentBy, string SentByIPAddress);
        DataSet getAdminSentSMSs(string Flag);
        DataSet getRONonRepliedMessages(string Flag, string LoginID);
        DataSet getRORepliedMessages(string Flag, string LoginID);
        DataSet getROSentMessages(string Flag, string LoginID);
        bool roComposeMessage(string To, string From, string Message, string FilePath1, string FilePath2, string SentBy, string SentByIPAddress);
        DataSet getInstituteNonRepliedMessages(string InstituteCode);
        DataSet getInstituteBroadcastedMessages(string InstituteCode);
        DataSet getInstituteRepliedMessages(string InstituteCode);
        bool instituteComposeMessage(string To, string From, string Subject, string Message, string FilePath1, string FilePath2, string SentBy, string SentByIPAddress);

        Int64 getPersonalID(string ApplicationID);
        string getCandidateName(Int64 PID);
        bool resetCandidatePasswordByAdmin(Int64 PID, string CandidatePassword, string PasswordResetBy, string PasswordResetByIPAddress);
        bool updateUserAction(string UserLoginID, string ApplicationID, string ActionTaken, string Module, string IPAddress);
        DataSet getDashboardAFC(Int32 UserTypeID, string UserLoginID, string Flag);
        DataSet getDashboardARC(Int32 UserTypeID, string UserLoginID);
        DataSet getDashboardInstitute(Int32 UserTypeID, string UserLoginID);
        DataSet getCandidateDetailsForDisplay(Int64 PID);
        DataSet searchCandidate(string Query);
        DataSet getLoginDetails(string LoginID, Int32 UserTypeID);
        DataSet getMasterAFCList(Int32 UserTypeID, string UserLoginID);
        DataSet getNonAFCInstituteList(Int32 UserTypeID, string UserLoginID);
        bool addMasterAFC(Int64 InstituteID, string CreatedBy, string CreatedByIPAddress);
        bool deleteMasterAFC(Int64 InstituteID, string ModifiedBy, string ModifiedByIPAddress);
        bool isInstituteWorkingAsAFC(Int64 InstituteID);
        DataSet getAFCList(Int64 InstituteID);
        string addAFC(Int64 InstituteID, string AFCOfficerName, string AFCOfficerMobileNo, string Password, string CreatedBy, string CreatedByIPAddress);
        bool updateAFC(Int64 AFCID, string AFCOfficerName, string AFCOfficerMobileNo, string ModifiedBy, string ModifiedByIPAddress);
        bool deleteAFC(Int64 AFCID, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getSubAFCList(Int64 AFCID);
        string addSubAFC(Int64 AFCID, string SubAFCOfficerName, string SubAFCOfficerMobileNo, string Password, string CreatedBy, string CreatedByIPAddress);
        bool updateSubAFC(Int64 SubAFCID, string SubAFCOfficerName, string SubAFCOfficerMobileNo, string ModifiedBy, string ModifiedByIPAddress);
        bool deleteSubAFC(Int64 SubAFCID, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getROList(Int32 UserTypeID, string UserLoginID);
        DataSet getAFCList(Int32 UserTypeID, string UserLoginID);
        DataSet getSubAFCList(Int32 UserTypeID, string UserLoginID);
        string getPassword(Int32 UserTypeID, string LoginID);
        bool resetPassword(Int32 UserTypeID, string LoginID, string Password, string ModifiedBy, string ModifiedByIPAddress);
        bool saveAFCProfile(AFCProfile obj, string ModifiedBy, string ModifiedByIPAddress);
        bool updateAFCProfile(AFCProfile obj, string ModifiedBy, string ModifiedByIPAddress);
        AFCProfile getAFCProfile(string AFCCode);
        DataSet getAFCListReport();
        DataSet checkUser(string UserLoginID);
        DataSet getRegionWiseReport(string ConfirmationDate);
        Int16 getRegionID(Int64 ARCID);
        DataSet getAFCWiseReport(Int16 RegionID, string ConfirmationDate);
        Int32 getInstituteID(Int64 AFCID);
        DataSet getSubAFCWiseReport(Int16 RegionID, Int32 InstituteID);
        DataSet getConfirmationDateList();
        DataSet getDiscrepancyDateList(Int32 InstituteID, Int32 AFCID);
        DataSet getConfirmedCandidateList(Int16 RegionID, Int32 InstituteID, Int32 AFCID, string ConfirmationDate);
        DataSet getARCList(Int32 UserTypeID, string UserLoginID);
        DataSet getSubARCList(Int32 UserTypeID, string UserLoginID);

        Int64 checkApplicationStatus(string ApplicationID, Int32 VersionNo);
        bool updateDocumentSubmission(Int64 PID, string XMLString, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getDocumentList(Int64 PID, string SubmittedFlag);
        bool confirmApplicationForm(Int64 PID, Int32 IsCandidatureTypeChanged, Int32 IsCategoryChanged, Int32 IsPHTypeChanged, Int32 IsDefenceTypeChanged, Int32 IsMinorityChanged, Int32 IsEWSChanged, Int32 IsOrphanChanged, string Comments, string IsNCLReceiptSubmitted, DateTime NCLIssueDate, Int32 NCLValidUpto, Int32 IsTFWSChanged, string ConfirmedBy, string ConfirmedByIPAddress);
        bool confirmApplicationFormProvisionally(Int64 PID, Int32 IsCandidatureTypeChanged, Int32 IsCategoryChanged, Int32 IsPHTypeChanged, Int32 IsDefenceTypeChanged, Int32 IsMinorityChanged, Int32 IsEWSChanged, Int32 IsOrphanChanged, string Comments, string IsNCLReceiptSubmitted, DateTime NCLIssueDate, Int32 NCLValidUpto, Int32 IsTFWSChanged, string ConfirmedBy,string ConfirmedByIPAddress);
        bool isApplicationFormConfirmed(Int64 PID);
        DataSet getApplicationFormConfirmationDetails(Int64 PID);
        bool checkApplicationFormConfirmationDetails(Int64 PID, Int32 UserTypeID, string UserLoginID);
        DataSet getNCLDocumentDetails(Int64 PID);
        bool editConfirmedApplicationForm(Int64 PID, Int32 IsCandidatureTypeChanged, Int32 IsCategoryChanged, Int32 IsPHTypeChanged, Int32 IsDefenceTypeChanged, Int32 IsMinorityChanged, Int32 IsEWSChanged, Int32 IsOrphanChanged, string Comments, string IsNCLReceiptSubmitted, DateTime NCLIssueDate, Int32 NCLValidUpto, string ModifiedBy, string ModifiedByIPAddress);
        bool cancelConfirmedApplicationForm(Int64 PID, string ReasonForCancellation, string CancelledBy, string CancelledByIPAddress);
        bool checkDuplicateApplicationForm(Int64 PID);
        DataSet getDuplicateApplicationFormDetails(Int64 PID);
        bool sendSMSToCandidate(string From, string To, string SMSContent, string SentBy, string SentByIPAddress);
        bool editApplicationStatus(string ApplicationName, Int32 ApplicationStatus, string ModifiedBy, string ModifiedByIPAddress);
        Int64 getParentID(Int64 AFCID);

        bool saveImportantDates(string ActivityDetails, DateTime ActivityStartDate, string ActivityStartTime, DateTime ActivityEndDate, string ActivityEndTime, DateTime ActivityDisplayStartDateTime, DateTime ActivityDisplayEndDateTime, string ActivityType, string CreatedBy, string CreatedByIPAddress);
        bool editImportantDates(Int64 ActivityID, string ActivityDetails, DateTime ActivityStartDate, string ActivityStartTime, DateTime ActivityEndDate, string ActivityEndTime, DateTime ActivityDisplayStartDateTime, DateTime ActivityDisplayEndDateTime, string ActivityType, string ModifiedBy, string ModifiedByIPAddress);
        bool deleteImportantDates(Int64 ActivityID, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getImportantDates(Int64 ActivityID);
        DataSet getAllImportantDates();
        DataSet getImportantDates();
        DataSet getTopActiveImportantDates();
        Int32 getApplicationFeeDetails(Int32 CandidatureTypeID, Int32 CategoryID, Int32 PHTypeID, string AppliedForEWS);

        DataSet getReportsList();
        DataSet executeReport(Int64 ReportID);
        DataSet searchReport(string Query);
        DataSet getTableViewList();
        DataSet getRejectedKeyWordList();
        DataSet getColumnsList(string TableViewName);
        bool saveReportDetails(string ReportName, string ReportQuery, string CreatedBy, string CreatedByIPAddress);
        bool editReportDetails(Int64 ReportID, string ReportName, string ReportQuery, string ModifiedBy, string ModifiedByIPAddress);
        bool deleteReportDetails(Int64 ReportID, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getReportDetails(Int64 ReportID);

        bool saveCaste(string CasteName, string CasteSrNo, Int16 CategoryID);
        bool deleteCaste(Int32 CasteID);
        CasteList getCaste(Int32 CasteID);
        bool updateCaste(CasteList Caste);

        DataSet getInstituteList(Int32 UserTypeID, string UserLoginID);
        bool changeInstitutePassword(string InstituteCode, string OldPassword, string NewPassword);
        bool updateInstituteProfile(InstituteProfile obj, string ModifiedBy, string ModifiedByIPAddress);
        InstituteProfile getInstituteProfile(Int32 InstituteID);
        DataSet getInstituteProfileDS(Int32 InstituteID);
        string getInstitutePassword(string InstituteCode);
        bool resetInstitutePassword(string InstituteCode, string Password,string EncryptedPassword);
        DataSet getInstitutesDetailedList();
        InstituteSummary getInstituteSummary(string InstituteCode);
        DataSet getChoiceCodeListByInstitute(string InstituteCode);
        CourseInformation getCourseInformation(string ChoiceCode);
        bool saveCourseInformation(CourseInformation obj, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getInvalidSeatDistributionList();
        DataSet getAllChoiceCodeList();
        DataSet getNewChoiceCodesAvailable();
        DataSet getChoiceCodesAvailableForUpdate();
        DataSet getChoiceCodesAvailableForDelete();
        bool insertNewChoiceCodes(string ModifiedBy, string ModifiedByIPAddress);
        bool updateChoiceCodes(string ModifiedBy, string ModifiedByIPAddress);
        bool deleteChoiceCodes(string ModifiedBy, string ModifiedByIPAddress);
        DataSet getInstituteListReport(Int32 UserTypeID, string UserLoginID);
        DataSet getAllChoiceCodeListFromDTEPortalForInstitute(string InstituteCode);
        DataSet getInstituteHostelCapacityDetails(Int64 InstituteID);
        bool saveInstituteHostelCapacityDetails(Int64 InstituteID, Int32 BoysHostelCapacityIYear, Int32 GirlsHostelCapacityIYear, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getInstituteListHavingCourtCaseRemark();
        DataSet getChoiceCodeListByInstituteHavingCourtCaseRemark(string InstituteCode);
        string getInstituteName(string InstituteCode);
        string getCourseName(string ChoiceCode);
        DataSet getCompositeReportForAdmin(string Flag, string Flag2);
        DataSet getCompositeReportForRO(string RO, string Flag, string Flag2);
        DataSet getCompositeReportForInstitute(string InstituteCode, string Flag, string Flag2);
        DataSet getCompositeReport(string ChoiceCode, string ReportingStatus);
        DataSet getInstituteListForAllotmentDisplay();
        DataSet getAllotmentReportForAdmin();
        DataSet getAllotmentReportForRO(string RO);
        DataSet getAllotmentReportForInstitute(string InstituteCode);
        DataSet getAllotmentReport(string ChoiceCode);
        DataSet getInvalidSeatSurrenderList();
        string isCandidateAllottedThisInstitute(Int64 PID, Int32 UserTypeID, string UserLoginID);
        bool isCandidateReportedToARC(Int64 PID);
        DataSet getPersonalInformationForInstitute(Int64 PID);
        DataSet getReportingDetails(Int64 PID);
        DataSet getDocumentListForInstitute(Int64 PID);
        DataSet getInstituteFeeList(Int64 PID, string FeeType, string InstituteCode, string AdmissionPhase);
        DataSet getInstituteFeeDetails(Int64 FeeID);
        Int32 saveInstituteFeeDetails(InstituteFeeDetails obj, string CreatedBy, string CreatedByIPAddress, string AdmissionPhase);
        Int32 editInstituteFeeDetails(InstituteFeeDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        bool deleteInstituteFeeDetails(Int64 FeeID, string ModifiedBy, string ModifiedByIPAddress);
        bool updateDocumentSubmissionForInstitute(Int64 PID, string XMLString, string ModifiedBy, string ModifiedByIPAddress);
        bool confirmAdmission(Int64 PID, DateTime AdmissionDate, string Comments, string ReportedBy, string ReportedByIPAddress);
        DataSet getReportingDetails(Int64 PID, char ReportingStatus);
        DataSet getDocumentListForInstitute(Int64 PID, string SubmittedFlag);
        bool editAdmission(Int64 PID, DateTime AdmissionDate, string Comments, string ModifiedBy, string ModifiedByIPAddress);
        bool cancelAdmission(Int64 PID, Int64 CancellationCharge, string ReasonForCancellation, string CancelledBy, string CancelledByIPAddress);
        bool editCancelAdmission(Int64 PID, Int64 CancellationCharge, string ReasonForCancellation, string ModifiedBy, string ModifiedByIPAddress);
        bool IsAdmissionConfirmedAtInstitute(Int64 PID);
        bool isCandidateAdmittedInThisInstitute(Int64 PID, Int64 ChoiceCode, Int32 CAPRound, Int32 UserTypeID, string UserLoginID);

        string isCandidateAllottedThisInstituteCAPRound5(Int64 PID, Int32 UserTypeID, string UserLoginID);
        DataSet getReportingDetailsCAPRound5(Int64 PID);
        bool confirmAdmissionCAPRound5(Int64 PID, DateTime AdmissionDate, string Comments, string ReportedBy, string ReportedByIPAddress);
        string isCandidateAllottedThisInstituteByReportingStatus(Int64 PID, Int32 UserTypeID, string UserLoginID, char ReportingStatus);
        string isCandidateAllottedThisInstituteByCAPRound(Int64 PID, Int32 UserTypeID, string UserLoginID, string Flag);
        DataSet getReportingDetailsByCAPRound(Int64 PID, string Flag);
        bool confirmAdmissionByCAPRound(Int64 PID, DateTime AdmissionDate, string Comments, string ReportedBy, string ReportedByIPAddress, string Flag);
        DataSet getReportingDetailsByChoiceCode(Int64 PID, Int64 ChoiceCode, Int32 CAPRound, char ReportingStatus);
        bool confirmAdmissionByChoiceCode(Int64 PID, Int64 ChoiceCode, Int32 CAPRound, DateTime AdmissionDate, string Comments, string ReportedBy, string ReportedByIPAddress);
        bool editAdmissionByChoiceCode(Int64 PID, Int64 ChoiceCode, Int32 CAPRound, DateTime AdmissionDate, string Comments, string ModifiedBy, string ModifiedByIPAddress);
        bool cancelAdmissionByChoiceCode(Int64 PID, Int64 ChoiceCode, Int32 CAPRound, Int64 CancellationCharge, string ReasonForCancellation, string CancelledBy, string CancelledByIPAddress);
        bool editCancelAdmissionByChoiceCode(Int64 PID, Int64 ChoiceCode, Int32 CAPRound, Int64 CancellationCharge, string ReasonForCancellation, string ModifiedBy, string ModifiedByIPAddress);

        bool isCandidateEligibleForAdmissionAtIL(Int64 PID);
        bool isCandidateEligibleForAdmission(Int64 PID);
        string getAdmissionDetails(Int64 PID);
        string isCandidateAllottedThisInstituteIL(Int64 PID, Int32 UserTypeID, string UserLoginID);
        DataSet getInstituteListForAdmissionAtIL(Int32 UserTypeID, string UserLoginID);
        DataSet getChoiceCodeListByInstituteForAdmissionAtIL(Int64 PID, string InstituteCode);
        DataSet getAllChoiceCodeListByInstituteForAdmissionAtIL(string InstituteCode);
        DataSet getSeatTypeListForAdmissionAtIL(string InstituteCode);
        bool confirmAdmissionAtIL(Int64 PID, Int64 ChoiceCode, string SeatType, Int32 MeritNo, DateTime AdmissionDate, string Comments, string ReportedBy, string ReportedByIPAddress);
        bool editAdmissionAtIL(Int64 PID, Int64 ChoiceCode, string SeatType, Int32 MeritNo, DateTime AdmissionDate, string Comments, string ModifiedBy, string ModifiedByIPAddress);
        bool cancelAdmissionAtIL(Int64 PID, Int64 ChoiceCode, Int64 CancellationCharge, string ReasonForCancellation, string CancelledBy, string CancelledByIPAddress);
        bool editCancelAdmissionAtIL(Int64 PID, Int64 ChoiceCode, Int64 CancellationCharge, string ReasonForCancellation, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getReportingDetailsAtIL(Int64 PID, Int64 ChoiceCode, char ReportingStatus);
        DataSet getReportingDetailsAtIL(Int64 PID, char ReportingStatus, Int32 UserTypeID, string UserLoginID, string Flag, string Code);
        DataSet getReportingDetailsAtCAP(Int64 PID, char ReportingStatus, Int32 UserTypeID, string UserLoginID, string Flag, string Code);

        DataSet getCandidateDetailsForDisplayInOptionForm(Int64 PID);
        DataSet getCourseListByPID(Int32 CAPRound, Int64 PID);
        DataSet getUniversityListByPID(Int32 CAPRound, Int64 PID);
        DataSet getInstituteListByUniversityID(Int32 CAPRound, Int64 PID, Int16 UniversityID);
        DataSet getChoiceCodeListByInstituteID(Int32 CAPRound, Int64 PID, Int32 InstituteID);
        DataSet getCancelledOptionFormReport(Int32 UserTypeID, string UserLoginID, Int32 CAPRound);
        Int64 authenticateApplicationIDnDOB(string ApplicationID, DateTime DOB);
        DataSet getChangeEligibilityReport(Int32 UserTypeID, string UserLoginID, Int32 CAPRound);
        DataSet verifyChoiceCode(Int32 CAPRound, Int64 PID, string ChoiceCodeDisplay);

        DataSet getCurrentLinkCAPRound1(Int64 PID, string URL);
        DataSet getCandidateStepListCAPRound1(Int64 PID);
        DataSet getSelectedOptionsListCAPRound1(Int64 PID);
        DataSet getOptionsListCAPRound1(Int64 PID, string CourseCode, Int16 UniversityID, string DistrictName, string CourseStatus1, string CourseStatus2, string CourseStatus3, string TFWSStatus);
        Int32 saveOptionsCAPRound1(Int64 PID, string OptionsList, string CreatedBy, string CreatedByIPAddress);
        Int32 deleteOptionsCAPRound1(Int64 PID, string OptionsList, string ModifiedBy, string ModifiedByIPAddress);
        Int32 saveShortlistedOptionsCAPRound1(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool checkPreferenceNoCAPRound1(Int64 PID);
        Int32 savePreferencesCAPRound1(Int64 PID, string PreferencesList, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getPreferancedOptionsListCAPRound1(Int64 PID);
        Int32 getPreferencesCountCAPRound1(Int64 PID);
        Int32 insertOptionCAPRound1(Int64 PID, Int32 PreferenceNo, Int64 ChoiceCode, string CreatedBy, string CreatedByIPAddress);
        Int32 insertOptionDirectCAPRound1(Int64 PID, Int32 PreferenceNo, string ChoiceCodeDisplay, string CreatedBy, string CreatedByIPAddress);
        Int32 moveOptionCAPRound1(Int64 PID, Int32 PreferenceNo, Int64 ChoiceCode, string ModifiedBy, string ModifiedByIPAddress);
        Int32 confirmOptionFormCAPRound1(Int64 PID, string CandidatePassword, string ConfirmedBy, string ConfirmedByIPAddress);
        DataSet getPersonalInformationCAPRound1(Int64 PID);
        DataSet getPreferancedOptionsListForDisplayCAPRound1(Int64 PID);
        DataSet getInstructionsCAPRound1(Int64 PID);
        DataSet getOptionFormConfirmationDetailsCAPRound1(Int64 PID);
        bool isOptionFormConfirmedCAPRound1(Int64 PID);
        bool cancelOptionFormCAPRound1(Int64 PID, String Comments, string CancelledBy, string CancelledByIPAddress);
        bool isCandidateEligibleCAPRound1(Int64 PID);
        bool changeCandidateEligibilityCAPRound1(Int64 PID, Int32 EligibilityStatus, string ModifiedBy, string ModifiedByIPAddress);
        bool isOptionFormCancelledBeforeCAPRound1(Int64 PID);
        bool saveOptionFormSummaryStepIDCAPRound1(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        string getInvalidChoiceCodeListCAPRound1(Int64 PID);
        bool isCandidateSelectedOptionsCAPRound1(Int64 PID);

        DataSet getAllotmentStatusCAPRound1(string ApplicationID, DateTime DOB);
        DataSet getAllotmentListCAPRound1();
        DataSet getAllotmentStatusCAPRound2(string ApplicationID, DateTime DOB);
        DataSet getAllotmentListCAPRound2();
        DataSet getAllotmentStatusCAPRound3(string ApplicationID, DateTime DOB);
        DataSet getAllotmentListCAPRound3();
        DataSet getAllotmentStatusCAPRound4(string ApplicationID, DateTime DOB);
        DataSet getAllotmentListCAPRound4();
        DataSet getFinalAllotmentStatus(string ApplicationID, DateTime DOB);
        DataSet getFinalAllotmentList();
        DataSet getAllotmentStatusCAPRound5(string ApplicationID, DateTime DOB);
        DataSet getAllotmentListCAPRound5();

        DataSet getImportOptionsFromCAPRound1(Int64 PID);
        bool importOptionsFromCAPRound1(Int64 PID, string CreatedBy, string CreatedByIPAddress);
        DataSet getCurrentLinkCAPRound2(Int64 PID, string URL);
        DataSet getCandidateStepListCAPRound2(Int64 PID);
        DataSet getSelectedOptionsListCAPRound2(Int64 PID);
        DataSet getOptionsListCAPRound2(Int64 PID, string CourseCode, Int16 UniversityID, string DistrictName, string CourseStatus1, string CourseStatus2, string CourseStatus3, string TFWSStatus);
        Int32 saveOptionsCAPRound2(Int64 PID, string OptionsList, string CreatedBy, string CreatedByIPAddress);
        Int32 deleteOptionsCAPRound2(Int64 PID, string OptionsList, string ModifiedBy, string ModifiedByIPAddress);
        Int32 saveShortlistedOptionsCAPRound2(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool checkPreferenceNoCAPRound2(Int64 PID);
        Int32 savePreferencesCAPRound2(Int64 PID, string PreferencesList, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getPreferancedOptionsListCAPRound2(Int64 PID);
        Int32 getPreferencesCountCAPRound2(Int64 PID);
        Int32 insertOptionCAPRound2(Int64 PID, Int32 PreferenceNo, Int64 ChoiceCode, string CreatedBy, string CreatedByIPAddress);
        Int32 insertOptionDirectCAPRound2(Int64 PID, Int32 PreferenceNo, string ChoiceCodeDisplay, string CreatedBy, string CreatedByIPAddress);
        Int32 moveOptionCAPRound2(Int64 PID, Int32 PreferenceNo, Int64 ChoiceCode, string ModifiedBy, string ModifiedByIPAddress);
        Int32 confirmOptionFormCAPRound2(Int64 PID, string CandidatePassword, string ConfirmedBy, string ConfirmedByIPAddress);
        DataSet getPersonalInformationCAPRound2(Int64 PID);
        DataSet getPreferancedOptionsListForDisplayCAPRound2(Int64 PID);
        DataSet Getreceiptcandidates(Int64 PID);
        DataSet getInstructionsCAPRound2(Int64 PID);
        DataSet getOptionFormConfirmationDetailsCAPRound2(Int64 PID);
        bool isOptionFormConfirmedCAPRound2(Int64 PID);
        bool cancelOptionFormCAPRound2(Int64 PID, String Comments, string CancelledBy, string CancelledByIPAddress);
        bool isCandidateEligibleCAPRound2(Int64 PID);
        bool changeCandidateEligibilityCAPRound2(Int64 PID, Int32 EligibilityStatus, string ModifiedBy, string ModifiedByIPAddress);
        bool isOptionFormCancelledBeforeCAPRound2(Int64 PID);
        bool saveOptionFormSummaryStepIDCAPRound2(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        string getInvalidChoiceCodeListCAPRound2(Int64 PID);
        bool isCandidateSelectedOptionsCAPRound2(Int64 PID);

        DataSet getImportOptionsFromCAPRound2(Int64 PID);
        bool importOptionsFromCAPRound2(Int64 PID, string CreatedBy, string CreatedByIPAddress);
        DataSet getCurrentLinkCAPRound3(Int64 PID, string URL);
        DataSet getCandidateStepListCAPRound3(Int64 PID);
        DataSet getSelectedOptionsListCAPRound3(Int64 PID);
        DataSet getOptionsListCAPRound3(Int64 PID, string CourseCode, Int16 UniversityID, string DistrictName, string CourseStatus1, string CourseStatus2, string CourseStatus3, string TFWSStatus);
        Int32 saveOptionsCAPRound3(Int64 PID, string OptionsList, string CreatedBy, string CreatedByIPAddress);
        Int32 deleteOptionsCAPRound3(Int64 PID, string OptionsList, string ModifiedBy, string ModifiedByIPAddress);
        Int32 saveShortlistedOptionsCAPRound3(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool checkPreferenceNoCAPRound3(Int64 PID);
        Int32 savePreferencesCAPRound3(Int64 PID, string PreferencesList, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getPreferancedOptionsListCAPRound3(Int64 PID);
        Int32 getPreferencesCountCAPRound3(Int64 PID);
        Int32 insertOptionCAPRound3(Int64 PID, Int32 PreferenceNo, Int64 ChoiceCode, string CreatedBy, string CreatedByIPAddress);
        Int32 insertOptionDirectCAPRound3(Int64 PID, Int32 PreferenceNo, string ChoiceCodeDisplay, string CreatedBy, string CreatedByIPAddress);
        Int32 moveOptionCAPRound3(Int64 PID, Int32 PreferenceNo, Int64 ChoiceCode, string ModifiedBy, string ModifiedByIPAddress);
        Int32 confirmOptionFormCAPRound3(Int64 PID, string CandidatePassword, string ConfirmedBy, string ConfirmedByIPAddress);
        DataSet getPersonalInformationCAPRound3(Int64 PID);
        DataSet getPreferancedOptionsListForDisplayCAPRound3(Int64 PID);
        DataSet getInstructionsCAPRound3(Int64 PID);
        DataSet getOptionFormConfirmationDetailsCAPRound3(Int64 PID);
        bool isOptionFormConfirmedCAPRound3(Int64 PID);
        bool cancelOptionFormCAPRound3(Int64 PID, String Comments, string CancelledBy, string CancelledByIPAddress);
        bool isCandidateEligibleCAPRound3(Int64 PID);
        bool changeCandidateEligibilityCAPRound3(Int64 PID, Int32 EligibilityStatus, string ModifiedBy, string ModifiedByIPAddress);
        bool isOptionFormCancelledBeforeCAPRound3(Int64 PID);
        bool saveOptionFormSummaryStepIDCAPRound3(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        string getInvalidChoiceCodeListCAPRound3(Int64 PID);
        bool isCandidateSelectedOptionsCAPRound3(Int64 PID);

        DataSet getCurrentLinkCAPRound4(Int64 PID, string URL);
        DataSet getCandidateStepListCAPRound4(Int64 PID);
        DataSet getSelectedOptionsListCAPRound4(Int64 PID);
        DataSet getOptionsListCAPRound4(Int64 PID, string CourseCode, Int16 UniversityID, string DistrictName, string CourseStatus1, string CourseStatus2, string CourseStatus3, string TFWSStatus);
        Int32 saveOptionsCAPRound4(Int64 PID, string OptionsList, string CreatedBy, string CreatedByIPAddress);
        Int32 deleteOptionsCAPRound4(Int64 PID, string OptionsList, string ModifiedBy, string ModifiedByIPAddress);
        Int32 saveShortlistedOptionsCAPRound4(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool checkPreferenceNoCAPRound4(Int64 PID);
        Int32 savePreferencesCAPRound4(Int64 PID, string PreferencesList, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getPreferancedOptionsListCAPRound4(Int64 PID);
        Int32 getPreferencesCountCAPRound4(Int64 PID);
        Int32 insertOptionCAPRound4(Int64 PID, Int32 PreferenceNo, Int64 ChoiceCode, string CreatedBy, string CreatedByIPAddress);
        Int32 insertOptionDirectCAPRound4(Int64 PID, Int32 PreferenceNo, string ChoiceCodeDisplay, string CreatedBy, string CreatedByIPAddress);
        Int32 moveOptionCAPRound4(Int64 PID, Int32 PreferenceNo, Int64 ChoiceCode, string ModifiedBy, string ModifiedByIPAddress);
        Int32 confirmOptionFormCAPRound4(Int64 PID, string CandidatePassword, string ConfirmedBy, string ConfirmedByIPAddress);
        DataSet getPersonalInformationCAPRound4(Int64 PID);
        DataSet getPreferancedOptionsListForDisplayCAPRound4(Int64 PID);
        DataSet getInstructionsCAPRound4(Int64 PID);
        DataSet getOptionFormConfirmationDetailsCAPRound4(Int64 PID);
        bool isOptionFormConfirmedCAPRound4(Int64 PID);
        bool cancelOptionFormCAPRound4(Int64 PID, String Comments, string CancelledBy, string CancelledByIPAddress);
        bool isCandidateEligibleCAPRound4(Int64 PID);
        bool changeCandidateEligibilityCAPRound4(Int64 PID, Int32 EligibilityStatus, string ModifiedBy, string ModifiedByIPAddress);
        bool isOptionFormCancelledBeforeCAPRound4(Int64 PID);
        bool saveOptionFormSummaryStepIDCAPRound4(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        string getInvalidChoiceCodeListCAPRound4(Int64 PID);
        bool isCandidateSelectedOptionsCAPRound4(Int64 PID);

        string getSeatAcceptanceStatus(Int64 PID);

        DataSet getCandidateStepListCAPRound5(Int64 PID);
        DataSet getSelectedOptionsListCAPRound5(Int64 PID);
        DataSet getOptionsListCAPRound5(Int64 PID, string CourseCode, Int16 UniversityID, string DistrictName, string CourseStatus1, string CourseStatus2, string CourseStatus3);
        Int32 saveOptionsCAPRound5(Int64 PID, string OptionsList, string CreatedBy, string CreatedByIPAddress);
        Int32 deleteOptionsCAPRound5(Int64 PID, string OptionsList, string ModifiedBy, string ModifiedByIPAddress);
        Int32 saveShortlistedOptionsCAPRound5(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool checkPreferenceNoCAPRound5(Int64 PID);
        Int32 savePreferencesCAPRound5(Int64 PID, string PreferencesList, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getPreferancedOptionsListCAPRound5(Int64 PID);
        Int32 getPreferencesCountCAPRound5(Int64 PID);
        Int32 insertOptionCAPRound5(Int64 PID, Int32 PreferenceNo, Int64 ChoiceCode, string CreatedBy, string CreatedByIPAddress);
        Int32 insertOptionDirectCAPRound5(Int64 PID, Int32 PreferenceNo, string ChoiceCodeDisplay, string CreatedBy, string CreatedByIPAddress);
        Int32 moveOptionCAPRound5(Int64 PID, Int32 PreferenceNo, Int64 ChoiceCode, string ModifiedBy, string ModifiedByIPAddress);
        Int32 confirmOptionFormCAPRound5(Int64 PID, string CandidatePassword, string ConfirmedBy, string ConfirmedByIPAddress);
        DataSet getPersonalInformationCAPRound5(Int64 PID);
        DataSet getPreferancedOptionsListForDisplayCAPRound5(Int64 PID);
        DataSet getInstructionsCAPRound5(Int64 PID);
        DataSet getOptionFormConfirmationDetailsCAPRound5(Int64 PID);
        bool isOptionFormConfirmedCAPRound5(Int64 PID);
        bool cancelOptionFormCAPRound5(Int64 PID, String Comments, string CancelledBy, string CancelledByIPAddress);
        bool isCandidateEligibleCAPRound5(Int64 PID);
        bool changeCandidateEligibilityCAPRound5(Int64 PID, Int32 EligibilityStatus, string ModifiedBy, string ModifiedByIPAddress);
        bool isOptionFormCancelledBeforeCAPRound5(Int64 PID);

        DataSet getSeatAcceptanceFeeList(Int64 PID);
        DataSet getSeatAcceptanceFeeList(Int64 PID, string FeeType);
        DataSet getSeatAcceptanceFeeDetails(Int64 FeeID);
        DataSet getSeatAcceptanceFeeDetails(Int64 PID, string FeeType, string FeeLockStatus);
        bool saveSeatAcceptanceFeeDetails(Int64 PID, SeatAcceptanceFeeDetails obj, string CreatedBy, string CreatedByIPAddress);
        bool editSeatAcceptanceFeeDetails(SeatAcceptanceFeeDetails obj, string ModifiedBy, string ModifiedByIPAddress);
        string getSeatAcceptanceConfirmationStatus(Int64 PID);
        DataSet getPersonalInformationForAllotmentDisplay(Int64 PID);
        DataSet getAllotmentDetails(Int64 PID);
        bool isEligibleForSeatAcceptance(Int64 PID, Int32 CAPRound);
        DataSet getSeatAcceptanceStatusDetails(Int64 PID);
        DataSet getOptionsListAvailableForBetterment(Int64 PID, Int32 CAPRound, string SeatAcceptanceStatus);
        Int32 getPreferenceNoAllotted(Int64 PID, Int32 CAPRound);
        bool saveSeatAcceptanceStatusDetails(Int64 PID, string SeatAcceptanceStatus, Int32 CAPRound, string ModifiedBy, string ModifiedByIPAddress);
        bool editSeatAcceptanceStatusDetails(Int64 PID, string SeatAcceptanceStatus, Int32 CAPRound, string ModifiedBy, string ModifiedByIPAddress);
        Int32 getSeatAcceptanceFeePaidAmount(Int64 PID);

        Int64 checkSeatAcceptanceStatus(string ApplicationID, Int32 VersionNo, Int32 CAPRound);
        bool confirmSeatAcceptanceForm(Int64 PID, string XMLString, string ReportingComments, Int32 ReportedCAPRound, string ConfirmedBy, string ConfirmedByIPAddress);
        bool isSeatAcceptanceFormConfirmed(Int64 PID);
        bool checkSeatAcceptanceFormConfirmationDetails(Int64 PID, Int32 UserTypeID, string UserLoginID);
        bool cancelSeatAcceptanceForm(Int64 PID, string ReasonForCancellation, string CancelledChequeFilePath, string AccountNumber, string IFSCCode, string CancelledBy, string CancelledByIPAddress);
        bool isSeatAcceptanceFormCancelled(Int64 PID);
        DataSet getRegionWiseARCReport();
        Int16 getARCRegionID(Int64 ARCID);
        DataSet getARCWiseReport(Int16 RegionID);
        Int32 getARCInstituteID(Int64 ARCID);
        DataSet getSubARCWiseReport(Int16 RegionID, Int32 InstituteID);
        DataSet getARCConfirmationDateList();
        DataSet getARCConfirmedCandidateList(Int16 RegionID, Int32 InstituteID, Int32 ARCID, string ConfirmationDate);
        string getAllotmentCancellationRemark(Int64 PID, Int32 CAPRound);
        bool saveAllotmentCancellationRemark(Int64 PID, Int32 CAPRound, string CancellationRemark, string ModifiedBy, string ModifiedByIPAddress);

        bool isEligibleForJKCounseling(Int64 PID);
        bool isSeatOfferedForJKCounseling(Int64 PID);
        bool isOfferedSeatCancelledForJKCounseling(Int64 PID);
        DataSet getPersonalInformationForJKCounseling(Int64 PID);
        DataSet getChoiceCodeListForJKCounseling(Int64 PID, string ChoiceCode);
        bool offerSeatForJKCounseling(Int64 PID, string ChoiceCodeOffered, string Comments, string ConfirmedBy, string ConfirmedByIPAddress);
        DataSet getOfferedSeatDetailsForJKCounseling(Int64 PID);
        bool editOfferedSeatForJKCounseling(Int64 PID, string ChoiceCodeOffered, string Comments, string ModifiedBy, string ModifiedByIPAddress);
        bool cancelOfferedSeatForJKCounseling(Int64 PID, string Comments, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getOfferedSeatCancellationDetailsForJKCounseling(Int64 PID);
        DataSet getOfferedSeatReportForJKCounseling(Int32 UserTypeID, string UserLoginID);
        DataSet getOfferedSeatCancellationReportForJKCounseling(Int32 UserTypeID, string UserLoginID);
        DataSet getVacantInstituteListForJKCounseling();
        string getTotalVacancyForJKCounseling();
        DataSet getMeritListForJKCounseling();
        DataSet getAllotmentCancellationRemarkReport();

        DataSet getGroupByListForMISReport();
        DataSet getMISReport(string Query);
        DataSet downloadAdmittedCandidateData(Int32 InstituteID);
        DataSet getCompositeReportByCategory(string Flag);
        DataSet getCompositeReportByCourse(string Flag);
        DataSet getCompositeReportByDistrict(string Flag);
        DataSet getCompositeReportByGender(string Flag);
        DataSet getCompositeReportByReligion(string Flag);
        DataSet getCompositeReportByUniversity(string Flag);
        string getIntakeForChoiceCode(string ChoiceCode);
        DataSet getCompositeReportByChoiceCode(string ChoiceCode);
        DataSet getAdmittedCandidateListToSubmit(string ChoiceCode);
        DataSet getSupernumeraryCandidateData(Int32 UserTypeID, string UserLoginID);

        bool isCandidateInterestedInAdmissionCancellation(Int64 PID, Int64 ChoiceCode, Int32 CAPRound);
        Int64 authenticateCandidateLogin(string ApplicationID, string Password);
        bool saveWillingnessForAdmissionCancellation(Int64 PID, Int64 ChoiceCode, Int32 CAPRound, string CandidatePassword, string RequestedBy, string RequestedByIPAddress);
        DataSet getCandidateListRequestedForAdmissionCancellation(Int32 UserTypeID, string UserLoginID);
        DataSet getAdmittedChoiceCodeListForCancellation(Int64 PID);
        DataSet getAdmittedChoiceCodeDetailsForCancellation(Int64 PID, Int64 ChoiceCode, Int32 CAPRound);
        DataSet getRequestedForAdmissionCancellationChoiceCodeList(Int64 PID);
        DataSet getRequestedForAdmissionCancellationChoiceCodeDetails(Int64 PID, Int64 ChoiceCode, Int32 CAPRound);

        bool saveFAQs(string Question, string Answer, string FAQType, Int32 SeqNo, string CreatedBy, string CreatedByIPAddress);
        bool editFAQs(Int64 FAQID, string Question, string Answer, string FAQType, Int32 SeqNo, string ModifiedBy, string ModifiedByIPAddress);
        bool deleteFAQs(Int64 FAQID, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getFAQDetails(Int64 FAQID);
        DataSet getFAQs();
        DataSet getFAQsListForDisplay();

        DataSet getMasterARCList(Int32 UserTypeID, string UserLoginID);
        DataSet getNonARCInstituteList(Int32 UserTypeID, string UserLoginID);
        bool addMasterARC(Int64 InstituteID, string CreatedBy, string CreatedByIPAddress);
        bool deleteMasterARC(Int64 InstituteID, string ModifiedBy, string ModifiedByIPAddress);
        bool isInstituteWorkingAsARC(Int64 InstituteID);
        DataSet getARCList(Int64 InstituteID);
        string addARC(Int64 InstituteID, string ARCOfficerName, string ARCOfficerMobileNo, string Password, string CreatedBy, string CreatedByIPAddress);
        bool updateARC(Int64 ARCID, string ARCOfficerName, string ARCOfficerMobileNo, string ModifiedBy, string ModifiedByIPAddress);
        bool deleteARC(Int64 ARCID, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getSubARCList(Int64 ARCID);
        string addSubARC(Int64 ARCID, string SubARCOfficerName, string SubARCOfficerMobileNo, string Password, string CreatedBy, string CreatedByIPAddress);
        bool updateSubARC(Int64 SubARCID, string SubARCOfficerName, string SubARCOfficerMobileNo, string ModifiedBy, string ModifiedByIPAddress);
        bool deleteSubARC(Int64 SubARCID, string ModifiedBy, string ModifiedByIPAddress);
        bool saveARCProfile(ARCProfile obj, string ModifiedBy, string ModifiedByIPAddress);
        bool updateARCProfile(ARCProfile obj, string ModifiedBy, string ModifiedByIPAddress);
        ARCProfile getARCProfile(string ARCCode);
        bool changeARCPassword(string LoginID, string Password, string PasswordResetByIPAddress);
        DataSet getARCListReport();

        DataSet getHSCResult(string hscSeatNo, string Name, string MotherName, string PassingYear);

        DataSet getMasterJuridiction(string DocumentType);
        DataSet getMasterDistrictForJuridiction(int JurisdictionID);

        bool updateInstitueParticipationInAditionalRound(Int64 InstitueID, string ParticipationInAditionalRound, string UpdatedBy, string UpdatedByIPAddress);
        bool getInstitueParticipationInAditionalRound(Int64 InstitueID);
        DataSet getInstitueAllotedCandidateACAP(string InstitueID, string ChoiceCode);
        Int32 updateInstitueAllotedCandidateACAPSeatType(Int64 PersonalID, string ChoiceCode, string SelectedSeatType, string UpdatedBy, string UpdatedByIPAddress);
        DataSet getVacancyForAdditionRoundByFlag(string ChoiceCode, string Flag);


        bool saveProjectConfigurationDetails(string AppKey, string AppValue, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getProjectConfigurationDetails(string AppKey);
        DataSet getProjectConfigurationList();
        string getProjectConfiguration(string AppKey);
        bool saveActivityStatusDetails(string ActivityName, DateTime? ActivityStartDateTime, DateTime? ActivityEndDateTime, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getActivityStatusDetails(string ActivityName);
        DataSet getActivityStatusList();
        DataSet getActivityStatus(string ActivityName);

        DataSet getApplicationFormLinksStatus(Int64 PID);
        string getCategoryName(Int64 PID);
        string getAppliedForEWSFlag(Int64 PID);
        bool isOrphanAndNotEligibleForCategoryReservation(Int64 PID);
        string getOriginalAppliedForEWSFlag(Int64 PID);
        Int32 getReligiousMinorityID(Int64 PID);
        Int32 getLinguisticMinorityID(Int64 PID);
        DataSet CheckOtp(Int64 PID, int OTPType);
        bool SaveOTP(Int64 PID, int OTP, int OTPType, bool Isused, DateTime validtill, string moileNo, string EmailId, string ModifiedBy, string ModifiedByIPAddress, int IsOTPVerificationRequired);


        string getRazorpayCustormerID(Int64 PID);
        string updateRazorpayCustormerID(Int64 PID, string RazorpayCustomerID);
        string ValidateDuplicateResponsebyRefNo(string RefNo);
        DataSet GetSMSEmailContent(Int64 PID, string Flag, string IPAddress, int IsOTPVerificationRequired);
        DataSet getApplicationFeePaymentDetails(Int64 PID);
        string getAnnualFamilyIncomeDetails(Int64 PID);
        DateTime getApplicationFormCreatedDate(Int64 PID);
        DataSet GetIncorrectNEETDetailsCandidate(Int64 PID);

        bool CheckCandidateCVCStatus(Int64 PID);
        bool CategoryConverttoOPEN(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool UpdateCategoryConverttoOPEN(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        DataSet GetCvcTvcReport();

        DataSet getAllotmentStatusCAPRound2ByPID(Int64 PID);
        DataSet getAllotmentStatusCAPRound3ByPID(Int64 PID);
        Int32 insertOptionDirectCAPRound3_SpecialChoiceAfterConfirm(Int64 PID, Int32 PreferenceNo, string ChoiceCodeDisplay, string CreatedBy, string CreatedByIPAddress);
        DataSet getILSeatAcceptanceFeeNotPaidReport(Int32 UserTypeID, string UserLoginID);
        DataSet getCategoryConversionFeeNotPaidReport(string UserLoginID);
        DataSet getDataForReminderSMS(string systemName);
        DataSet getApplicationFormCancellationDetails(Int64 PID);
        bool SaveMasterTemplateFiled(string name);
        DataSet getEmailSMSTemplateBySystemName(string systemName);
        bool updateSMSEmailTemplates(string template, string systemName, string CreatedBy, string CreatedByIPAddress);
        bool updateSMSEmailTemplates(Int64 Id, string name, string template, string type, string systemName, string CreatedBy, string CreatedByIPAddress);
        DataSet getAllSMSEmailTemplates();
        DataSet getMasterPassingYear(string IsActive);
        bool chkDuplicateSMSEmailTemplateSystemName(string systemName);
        bool getSaveSMSEmailTemplates(string name, string template, string type, string systemName, string CreatedBy, string CreatedByIPAddress);
        DataSet getGetSMSEmailTemplates(string type, string systemName);
        DataSet getGetMaster_TemplateFields();
        List<Master_Village> getAllMasterVillage();
        List<Master_Taluka> getAllMasterTaluka();
        List<Master_District> getAllMasterDistrict();
        bool CandidateComposeMessage(string To, string From, string Subject, string Message, string FilePath1, string FilePath2, string SentBy, string SentByIPAddress);
       
        
        bool CheckCandidateValidForMessage(Int64 PersonalID);
        DataSet getMasterHSCSubject();
        DataSet GetRepliedMessagesToCandidateByAdmin(string CandidateCode);
        DataSet getCandidateNonRepliedMessages(string CandidateCode);
        DataSet getAdminNonRepliedMessages_Canidate(string Flag);
        DataSet getAdminRepliedMessagesToCandidate(string Flag);
        DataSet getMessagesListToCandidate(string From);
        bool replyMessageToCandidate(Int64 MessageID, string RepliedMessage, string RepliedBy, string RepliedByIPAddress, string To, string From, string FilePath1, string FilePath2);
        UpdateInstituteFormPortal getMasterofInstituteChoiceCodeUniversity();
        List<Master_Taluka> GetAllMasterMHTaluka();
        bool CheckFCVerificationStatus(Int64 PID);
        DataSet getVerificationFlags(Int64 PID);
        bool checkActiveTicketExist(Int64 PID);
        string CheckCandidateFCVerificationFor(Int64 PersonalID);
        string GetApplicationLockStatus(Int64 PersonalID);
        DataSet GetDocumentListByUploadedFlag(Int64 PID, string SubmittedFlag);
        bool saveUploadDocumentStepID(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool CheckBankDetailsStatus(Int64 PersonalID);
        bool SaveBankDetailsSkip(Int64 PersonalID, string CreatedBy, string CreatedByIPAddress, string DeviceInfo);
        bool SaveBankDetails(Int64 PersonalID, Int64 AadhaarNo, string BankName, string IFSCCODE, string BankAccountNo, string AccountHolderName, string CreatedBy, string CreatedByIPAddress, string DeviceInfo);
        DataSet GetBankDetailsStatus(Int64 PersonalID);
        DataSet GetMasterMHDistrictForFCVerification();
        DataSet GetCandidateBookingSlotDetails(Int64 PersonalID);
        DataSet GetSlotDates(string AFCCode);
        DataSet GetFCDetailsForSlotBooking(int DistrictID);
        DataSet GetSlotForFC(string FCID, string date);
        Int16 SaveCandidateBookedSlot(Int64 FCDateID, int SlotID, Int64 PersonalID, string CreatedBy, string CreatedByIpAddress);
        bool UpdateCandidateFCVerificationFor(Int64 PersonalID, string FCVerificationFor, string ModifiedBy, string ModifiedByIPAddress);
        bool UpdateCandidateBrowserOS(Int64 PersonalID, string BrowserOS);
        string getAppliedForTFWSFlag(Int64 PID);
        DataSet GetApplicationFormVersionNo(Int64 PID, string VersionNoFlag);
        PersonalInformation GetPersonalInformationByApplicationVersionNo(Int64 PID, Int32 VersionNo);
        List<DocumentDetails> GetPersonalInformationByApplicationVersionNoDocuments(Int64 PID, Int32 VersionNo);
        List<DocumentDetails> GetPersonalInformationByAcknowledgementVersionNoDocuments(Int64 PID, Int32 VersionNo);
        List<DiscrepancyDetails> GetAcknowledgementVersionNoDiscrepancy(Int64 PID, Int32 VersionNo);
        PersonalInformation GetPersonalInformationByAcknowledgementVersionNo(Int64 PID, Int32 VersionNo);

        DataSet isApplicationFormConfirmedUsingThisCETApplicationNo(Int64 CETApplicationFormNo, Int64 PID);
        DataSet isApplicationFormConfirmedUsingThisNEETRollNo(Int64 NEETRollNo, Int64 PID);
        //MAHA IT Document Fetch Start
        bool InsertUpdateDocumentFetchData(ResponseCommon obj);
        ResponseCommon GetDocumentFetchData(Int64 PersonalID, Int64 DocID);
        //MAHA IT Document Fetch END

        //E verification Start
        bool editConfirmedApplicationFormEvrification(Int64 PID, Int32 IsCandidatureTypeChanged, Int32 IsCategoryChanged, Int32 IsPHTypeChanged, Int32 IsDefenceTypeChanged, Int32 IsTFWSChanged, Int32 IsMinorityChanged, Int32 IsEWSChanged, Int32 IsOrphanChanged, string Comments, string IsNCLReceiptSubmitted, DateTime NCLIssueDate, Int32 NCLValidUpto, string ModifiedBy, string ModifiedByIPAddress);
        DataSet GetApplicationFormConfirmationDetailsGrivance(Int64 PID);
        bool SaveSubmitApplicationFormStepID(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool UnlockApplicationForm(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        //PersonalInformation GetPersonalInformationByApplicationVersionNo(Int64 PID, Int32 VersionNo);
        //List<DocumentDetails> GetPersonalInformationByApplicationVersionNoDocuments(Int64 PID, Int32 VersionNo);
        //List<DocumentDetails> GetPersonalInformationByAcknowledgementVersionNoDocuments(Int64 PID, Int32 VersionNo);
        //PersonalInformation GetPersonalInformationByAcknowledgementVersionNo(Int64 PID, Int32 VersionNo);
        //DataSet GetApplicationFormVersionNo(Int64 PID, string VersionNoFlag);
        DataSet GetCandidateVerificationStepwiseStatusForAFC(Int64 PID);
        DataSet GetDocumentListForDataVerificationByStepID(Int64 PID, Int32 ApplicationFormStepID);
        DataSet GetDocumentListForDocumentVerificationByStepID(Int64 PID, Int32 ApplicationFormStepID);
        DataSet GetDiscrepancyListByStepID(Int64 PID, int ApplicationFormStepID);
        bool UpdatePickedupStatus(Int64 PID, string UserLoginID, string ModifiedBy, string ModifiedByIPAddress);
        bool UpdateDiscrepancySubmission(Int64 PID, string XMLString, string ModifiedBy, string ModifiedByIPAddress);
        Int32 CheckDiscrepancyExists(Int64 PID);
        bool ConfirmApplicationFormWithDiscrepancy(Int64 PID, Int32 IsCandidatureTypeChanged, Int32 IsCategoryChanged, Int32 IsPHTypeChanged, Int32 IsDefenceTypeChanged, Int32 IsTFWSChanged, Int32 IsMinorityChanged, Int32 IsIGDChanged, Int32 IsEWSChanged, Int32 IsOrphanChanged, string Comments, DateTime NCLIssueDate, Int32 NCLValidUpto, string ConfirmedBy, string ConfirmedByIPAddress);
        DataSet GetDiscrepancyDetails(Int64 PID);
        DataSet GetApplicationFormListForFCReVerificationofGrievance(string UserLoginID, int UserTypeID);
        DataSet CheckFCForConfirmApplicationForm(string UserLoginID, long PersonalID, long ID, string IPAddress);
        string CheckISEFC(string AFCCode);
        DataSet GetSubAFCEConfirmedCount(int RegionID, int InstituteID);
        DataSet GetSubAFCDiscrepancyMarkedCount(int RegionID, int InstituteID);
        DataSet getRegionWiseApplicationFormListForFCVerification();
        DataSet getRequiredDocumentList(Int64 PID);
        DataSet GetEFCConfiredCandidateList(Int16 RegionID, Int32 InstituteID, Int32 AFCID, string ConfirmationDate);
        DataSet GetDiscrepancyMarkedCandidateList(Int16 RegionID, Int32 InstituteID, Int32 AFCID, string ConfirmationDate);
        DataSet GetApplicationFormListForPartialFCVerification(string UserLoginID, int UserTypeID);
        DataSet GetApplicationFormListForFCVerification(string UserLoginID, int UserTypeID);
        DataSet getAFCWiseApplicationFormListForFCVerification(Int16 RegionID);
        bool UnLockApplicationFormByCandidate(Int64 PersonalID, string CreatedBy, string CreatedByIpAddress);
        bool LockApplicationForm(Int64 PersonalID, string CreatedBy, string CreatedByIpAddress);
        bool CheckFCVerificationStatusForResubmission(Int64 PersonalID);
        DataSet GetCandidateEFCAllotted(Int64 PersonalID);
        DataSet GetAFCNonRepliedGrievance(string Flag, string To);
        DataSet getAFCWiseReport(Int16 RegionID);
        // DataSet GetCandidateEFCAllotted(Int64 PersonalID);

        DataSet GetRegionWiseConfirmationReport();
        DataSet GetEFCRegistrationandConfirmationStatusReport();
        DataSet GetApplicationFormStatistics();
        DataSet GetAFCWiseConfirmationReport(Int16 RegionID);
        bool CheckCETDiscrepancy(Int64 PersonalID);
        bool CheckNEETDiscrepancy(Int64 PersonalID);
        bool SolveCETDiscrepancy(Int64 PersonalID, Int64 CETApplicationFormNo, string CreatedBy, string CreatedByIpAddress);

        //E verification END
        //MessageBox

        DataSet getReplyMessageByMessageID(Int64 MessageID);
        DataSet getRepliedMessagesListToCandidate(string From);

        List<Fee_PaidFee> GetFailTransections(string PID);
        List<Fee_PaidFee> GetAllTransectionByPersonalID(string PID);
        bool UpdatePaymentReconcelation(Int64 ReferenceNo, Int64 PID, string PayGateId, string ModifiedBy);
        bool SaveSelfVerification(SelfVerification selfVerification);
        bool CheckSelfVerificationIsDone(Int64 PID);
        DataSet getHSCResult(string SeatNo, string PassingYear);
        DataSet CheckDiscrepancyDetailsCandidateureType(Int64 PID);
        DataSet GetSeatAcceptanceGrivanceStatusByPID(Int64 PersonalID);
        DataSet GetSubAFCWiseSeatAcceptanceGrievanceVerifcationCount(Int16 RegionID, Int32 InstituteID, Int32 CAPRound);
        DataSet GetSubAFCWiseSeatAcceptanceGrievanceRejectedCount(Int16 RegionID, Int32 InstituteID, Int32 CAPRound);
        DataSet GetSubAFCWiseSeatAcceptanceGrievancePickedupCount(Int16 RegionID, Int32 InstituteID, Int32 CAPRound);
        DataSet GetSubAFCWiseSeatAcceptanceGrievanceApprovedCount(Int16 RegionID, Int32 InstituteID, Int32 CAPRound);

        DataSet GetSeatAcceptanceGrievanceListForVerification(Int16 RegionID, Int32 InstituteID, Int32 AFCID, Int32 CAPRound);
        DataSet GetSeatAcceptanceRejectedGrievanceList(Int16 RegionID, Int32 InstituteID, Int32 AFCID, Int32 CAPRound);
        DataSet GetSeatAcceptancePickedupGrievanceList(Int16 RegionID, Int32 InstituteID, Int32 AFCID, Int32 CAPRound);
        DataSet GetSeatAcceptanceApprovedGrievanceList(Int16 RegionID, Int32 InstituteID, Int32 AFCID, Int32 CAPRound);

        DataSet GetRegionWiseSeatAcceptanceGrievanceStatus(string GrievanceStatusFlag, Int32 CAPRound);
        DataSet GetAFCWiseSeatAcceptanceGrievanceStatus(Int16 RegionID, string GrievanceStatusFlag, Int32 CAPRound);

        DataSet getSelfVerificationDetails(Int64 PID);
        DataSet GetSelfVerificationstatus(Int64 PersonalID);

        

        bool EditConfirmedApplicationFormSelfVerification(Int64 PID, Int32 CAPRound, string NewGenderCode,
             Int32 IsGenderChanged, Int32 IsCandidatureTypeChanged, Int32 IsCategoryChanged, Int32 IsEWSChanged, Int32 IsPHTypeChanged, Int32 IsDefenceTypeChanged, Int32 IsOrphanChanged,
             Int32 IsTFWSChanged, Int32 IsLinguisticMinorityChanged, Int32 IsReligiousMinorityChanged, Int32 IsIGDChanged,
             Int32 IsSSCMathematicsMarksChanged, Int32 IsSSCTotalMarksChanged, Int32 IsHSCPhysicsMarksChanged, Int32 IsHSCChemistryMarksChanged,
               Int32 IsHSCEnglishMarksChanged, Int32 IsHSCTotalMarksChanged, Int32 IsHSCSubjectMarksChanged, Int32 IsDiplomaMarksChanged,
             QualificationDetails obj,
             Int32 IsAllotmentCancelled, string RequestStatus, string Comments, string ModifiedBy, string ModifiedByIPAddress);

        bool UpdateSeatAcceptanceGrievanceStaus(Int64 PID, Int32 CAPRound, string RequestStatus, string Comments, string ModifiedBy, string ModifiedByIPAddress);

        DataSet GetRegionWiseSeatAcceptanceGrievanceConfirmationReport();
        DataSet GetAFCWiseSeatAcceptanceGrievanceConfirmationReport(Int16 RegionID);
        bool UpdateSeatAcceptanceGrievancePickedupStatus(Int64 PID, string UserLoginID, Int32 CAPRound, string ModifiedBy, string ModifiedByIPAddress);
        DataSet CheckFCForSeatAcceptanceGrievance(string UserLoginID, long PersonalID, long ID, string IPAddress);
        bool CategoryEWSConverttoOPEN(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool UpdateCategoryEWSConverttoOPEN(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        DataSet CheckCandidateValid(Int64 PID);

        DataSet CheckCandidateUpladedDoc(Int64 PID);

        bool CheckCandidateinAllotmentCancellationRemark(Int64 PID);
        bool CancelSelfVerificationSeatAcceptanceForm(Int64 PID, string UserLoginID, string IPAddress, string Comment);
        bool ConfirmCVCNCLEWSApplication(Int64 PID, string ModifiedBy, string ModifiedByIPAddress, string CVC, string NCL, string EWS);
        DataSet GetDocumentListForDataVerificationByStepIDCVCTVCNCLEWS(Int64 PID, Int32 ApplicationFormStepID);
        DataSet GetDocumentListForDocumentVerificationByStepIDCVCTVCNCLEWS(Int64 PID, Int32 ApplicationFormStepID);
        DataSet GetDiscrepancyListByStepIDCVCTVCNCLEWS(Int64 PID, int ApplicationFormStepID);
        DataSet getCVCNCLEWSReciptStatistic();
        Int16 UnlockOptionFormCAPRound2(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        Int16 CheckUnlockOptionFormCAPRound2(Int64 PID);
        string GetAdmissionCategory(Int64 PID);

        DataSet downloadRegisterdCandidateDataWithAdmissionDetails();
        DataSet GetDateWiseFCSlotBookingReport(int UserTypeID, string UserLoginID, string date);
        DataSet getFCWiseSlotBookingStausReport();
        DataSet GetDatewiseSlotsForFC(string UserLoginID);
        bool UpdateDatewiseCapacityForFC(Int64 FCDateID, int AvilableSlots, string ModifiedBy, string ModifiedByIPAddress);
        DataSet GetRegionwiseSlotBookingStausReport();
        DataSet GetFCWiseSlotBookingList(Int16 RegionID, Int32 InstituteID, Int32 AFCID, string ConfirmationDate);
        bool UpdateContactedDetailsFromFC(Int64 PersonalID, string Message, string ModifiedBy, string ModifiedByIPAddress);
        DataSet GetSlotSelectedNotConfirmedList(Int16 RegionID, Int32 InstituteID, Int32 AFCID, string ConfirmationDate);
        bool CheckIsSlotBooked(Int64 PersonalID);
        bool isApplicationFormConfirmedUsingThisEMailID(string EmailID, Int64 PID);
       DataSet getNEETResult(string NEETRollNo, string NEETDOB);
        DataSet getFeeDetailsForSupport(Int64 PID);
        DataSet GetApplicationFormAcknowledgeFormMaxVersionNo(Int64 PID, string VersionNoFlag);
        DataSet getStepIDforSupport(Int64 PID);
        DataSet GetDocStatusForSupport(Int64 PID);
        bool GetPreferancedOptionsListOnlyTFWSSelect(Int64 PID);
        string getBenefitTakenByCandidate(Int64 PID, Int32 CAPRound);
        DataSet GetNEETConfiredCandidateList(Int16 RegionID, Int32 InstituteID, Int32 AFCID, string ConfirmationDate);
        bool GetPreferancedOptionsListOnlyTFWSSelectCap2(Int64 PID);
        bool isContinueWithReceiptCandidateExist(Int64 PID);

        #region ARA_Module
        // FUNCTION FOR ARA MODULE
        Int32 getAdmissionApprovalFeePaidAmount(Int64 InstituteID);
        DataSet getAdmissionApprovalFeeDetails(Int64 InstituteID, string FeeType, string FeeLockStatus);
        bool saveAdmissionApprovalFeeDetails(Int64 InstituteID, AdmissionApprovalFeeDetails obj, string CreatedBy, string CreatedByIPAddress);
        Int32 getAdmissionApprovalFeeToBePaid(Int32 FeeGroupID, Int32 PhaseID, Int32 UserTypeID, Int64 PayeeID);
        DataSet getAdmissionApprovalFeeDetailsTable(Int32 FeeGroupID, Int32 PhaseID, Int32 UserTypeID, Int64 InstituteID);

        DataSet getARADashBoardForARAAdmin(string Flag);
        DataSet getARADashBoardForRO(string RO, string Flag);
        DataSet getARADashBoardForInstitute(string InstituteCode, string Flag);
        DataSet getROwiseAdmissionApprovalFeePaidDetails(string Flag);
        DataSet getInstitutewiseAdmissionApprovalFeePaidDetails(string ROName, string Flag);
        DataSet GetAdmittedCandidateListToROVerification(string ChoiceCode);
        DataSet GetAdmittedCandidateListToAraVerification(string ChoiceCode);
        DataSet GetAdmittedCandidateListToInstituteVerification(string ChoiceCode);
        DataSet GetDocumentListForInstituteToRo(Int64 PID);
        bool UpdateDocumentSubmissionForInstituteToRo(Int64 PID, string XMLString, string ModifiedBy, string ModifiedByIPAddress, string InstituteByRemar);
        //END OF FUNCTION FOR ARA MODULE
        #endregion

        DataSet getLoginData(string LoginID, string BrowserName, string BrowserVersion, string IPAddress);

        //Functions for MV Module
        DataSet getAllotedInstitutesForSO(string SOCode, int GrdNo);
        DataSet getCandidateListforMV(Int64 InstCode, string Flag);
        string addMVSO(string ScrutinyOfficerName, string ScrutinyOfficerMobileNo, string ScrutinyOfficerEmailID, string ScrutinyOfficerDesignation, string Password, string CreatedBy, string CreatedByIPAddress, int RegionID, string Password2);
        DataSet getMVSOList(Int64 RegionID);
        DataSet getInstituteList(Int64 RegionID);
        bool updateMVSO(Int64 SOID, string ScrutinyOfficerName, string ScrutinyOfficerMobileNo, string ScrutinyOfficerEmailId, string ScrutinyOfficerDesignation, string ModifiedBy, string ModifiedByIPAddress);
        bool deleteMVSO(Int64 SOID, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getInstitutelistSOMappingForRO(string RO, Char Flag);
        DataSet SaveInstituteMappingforSO(Int64 SOID, Int64 instituteID, string CreatedBy, string CreatedByIPAddress, Int64 ChoiceCode, Int64 ChoiceTFWS);
        DataSet UpdateInstituteMappingforSO(Int64 SOID, Int64 instituteID, string CreatedBy, string CreatedByIPAddress);
        DataSet getMasterMVDiscrepancy();
        bool saveMVDiscrepancy(MeritListVerificaton obj, string ModifiedBy, string ModifiedByIPAddress);
        bool saveInstituteVarificationStatus(Int64 InstCode, char Verified, string CreatedBy, string CreatedIPAddress, char Flg, string ChoiceCode);
        bool saveInstituteVarificationARA(Int64 InstCode, char Verified, string CreatedBy, string CreatedIPAddress, DateTime ApprovalDate);
        bool saveInstituteVarifyRODTE(Int64 InstCode, char Verified, string CreatedBy, string CreatedIPAddress, char Flg, string Remarks);
        MVSOProfile getMVSOProfile(Int64 SOID);
        DataSet getVerifiedBySO(Int64 SOID);
        DataSet getCandidateVerifiedBySO(Int64 SOID, string InstCode);
        DataSet getRODashboardForMV(string RO, Char Flag);
        DataSet getMVVerifyStatus(int SOID);
        DataSet getVerifiedByInst(Int64 InstCode, Char Flag);
        DataSet getMVSOLoad(Int64 SOID);
        DataSet getMLVCertificate(Int64 InstCode);
        bool updateCandidateSrNo(Int64 SRNO, Int64 PID);
        DataSet getDTEDashboardForMV(Char Flag);
        DataSet getSOStats(string SOCode);
        string getCertificateRemarks(string InstituteCode, char Flg);
        DataSet getAllotmentReportForSO(string ChoiceCode, string Flg);
        DataSet getCompositeReportForInstitute_ARAFeeReceipt(string InstituteCode, string Flag);
        bool saveProposalStatus(string InstCD, string Submitted, string CreatedBy, string CreatedIPAddress, DateTime ProposalDate);
        DataSet getARADashboardForMV(Char Flag);
        DataSet getMasterUserType();
        DataSet getMasterUserForReconciliation();
        bool chkDuplicateMasterUserName(string LoginId);
        bool addMasterUser(string UserName, string LoginId, string UserPassword, string EncryptedPassword, Int64 UserTypeId, string UserMobNo, string UserEmailId, string CreatedBy, string CreatedByIPAddress);
        DataSet CandidateApprovalReport(Int64 InstCode, string Flag);
        DataSet ARADashboardReport(string Flag);
        DataSet ProposalSubmittedInstitutes(string Region);
        DataSet ARAReportforMV(string Flag);
        DataSet ARAInstituteList(string Region);
        DataSet ARAFeesPaidInstitutes(string Region);
        DataSet ARAInstituteListConfirmedbyROAndDTE(string Region, string Flag);
        DataSet ARAVerificationDate(Int64 InstCode);
        string isApplicationFormRegisteredUsingThisMobileNo(string MobileNo, Int64 PID);
        DataSet getVerifyOTPVerificationAttemptsDetails(string ApplicationID, string ModifiedByIPAddress, int OTPType, string Template);
        bool CheckOldCandidatePassword(string LoginID, string OLDCandidatePassword);
        bool IsApplicationFormRegisteredUsingThisHSCSeatNo(Int64 PID, Int16 StepID, string HSCPassingYear, string HSCSeatNo, Int16 HSCBoardID);
        DataSet getHSCSeatNo(Int64 PID);
        DataSet GetApplicationIDIsFormRegisteredUsingHSCSeatNo(Int64 PID, string HSCPassingYear, string HSCSeatNo, Int16 HSCBoardID);
        DataSet IsApplicationFormRegisteredUsingThisNEETRollNo(Int64 PID, string NEETRollNo, Int16 StepID);
        DataSet ISApplicationFormRegisteredUsingThisCETApplicationNo(Int64 CETApplicationFormNo, Int16 StepID, Int64 PID);
        bool IsApplicationFormConfirmedUsingThisHSCSeatNo(Int64 PID);
        DataSet GetApplicationIDIsFormConfirmedUsingHSCSeatNo(Int64 PID);
        bool IsEditApplicationFormConfirmedUsingThisHSCSeatNo(Int64 PID);
        DataSet IsApplicationFormConfirmedUsingThisCETApplicationNoCheckCandidatureTyp(Int64 PID, Int16 CandidatureTypeID);
        DataSet EditApplicationFormConfirmedUsingThisCETApplicationNoCheckCandidatureTyp(Int64 PID, Int16 CandidatureTypeID);
        DataSet GetAdmissionCategoryforReceipt(Int64 PID);
        bool isCandidateNameAppearedInProvisionalMeritList(string ApplicationID);
        bool CheckCandidateCVCTVCEWSStatus(Int64 PID);
        bool ConfirmFCCVCNCLEWSApplication(Int64 PID, string ModifiedBy, string ModifiedByIPAddress, string CVC, string NCL, string EWS);
        bool checkApplicationFormModifiedDetailsForCVCTVCEWS(Int64 PID, Int32 UserTypeID, string UserLoginID);
        bool GetPreferancedOptionsListOnlyTFWSSelectCap3(Int64 PID);
        bool OnlyThisCandidateOperation(string ApplicationID);
        DataSet getAdmictionCancellationandAdmitedDetails(Int64 PID);
        bool CheckISOTPverifyed(Int64 PID, int OTPType);
        bool AuthenticateCandidateisActive(string ApplicationID);
        bool CheckIsVerifiedUseResetPassword(Int64 PID, int OTPType);
        DataSet getARAProcessFeeCandidateCount(Int32 FeeGroupID, Int32 PhaseID, Int32 UserTypeID, Int64 InstituteID);
        DataSet GetNotRecommendedList(string Flag, string Region);
        string getCandidateDOB(Int64 PID);
        bool GetFCRApplicationID(Int64 PID);
        bool UpdateFCRDetails(Int64 PID, string FCRApplicationID, string FCRCandidateName, string FCRCandidatureTypeName, string FCRMotherName, string FCRGender, DateTime FCRDOB);
        string GetTemplateNameUsedInEmailWhatsapp(string TemplateName, char Flag);
        bool ChangeFCVerificationMode(Int64 PID, string Flag, string ModifiedBy, string ModifiedByIPAddress);

        #region  #region Star Messages Changes
        DataSet getAdminStarRepliedMessages(string Flag);
        DataSet getStarMessagesList(string From);
        DataSet getReplyStarMessageByMessageID(Int64 MessageID);
        bool updateStarMessageStatus(Int64 MessageID);
        #endregion

        #region Ticketing System
        DataSet getMasterGrievanceCategory(Int32 UserTypeID);
        DataSet GetGrievanceDashboard(Int32 UserTypeID, string UserLoginID);
        Int64 SendGrievance(string ApplicationID, Int16 GrievanceCategoryID, string OtherGrievanceCategory, string Grievance, string GrievanceFileURL, string UserLoginID, string IPAddress);
        DataSet CheckGrievanceStatus(string UserLoginID, string Search);
        DataSet GetGrievanceList(Int64 GrievanceID);
        DataSet GetGrievanceListByStatus(Int32 UserTypeID, string UserLoginID, string GrievanceStatus, string Search, Int16 GrievanceCategoryID);
        string OpenGrievance(Int64 GrievanceID, Int32 UserTypeID, string UserLoginID, string IPAddress);
        Int64 GetFinalGrievanceID(Int64 GrievanceID, string Flag);
        DataSet GetGrievanceDetails(Int64 GrievanceID);
        string ForwardGrievance(Int64 GrievanceID, Int16 AssignedTo, string UserLoginID, string IPAddress);
        string ReplyGrievance(Int64 GrievanceID, string RepliedGrievance, string RepliedGrievanceFileURL, string UserLoginID, string IPAddress);
        string ReOpenGrievance(Int64 GrievanceID, string Grievance, string GrievanceFileURL, string UserLoginID, string IPAddress);

        #endregion

        DataSet GetDirectorReport();
        bool saveCETDetails(Int64 PersonalID, Int64 CETApplicationFormNo, string CreatedBy, string CreatedByIpAddress);
        bool UploadCorrectDocumentafterReporting(Int64 PID, string ModifiedBy, string ModifiedByIPAddress);
        bool GetSeatAcceptanceStatusforBettermentcandidate(Int64 PID);
        bool UpdateSeatAcceptanceStatusforBettermentcandidate(Int64 PID, string SeatAcceptanceStatus, Int32 CAPRound, string ModifiedBy, string ModifiedByIPAddress);
        DataSet getSeatAcceptanceStatusDetailsForBettermentCandidate(Int64 PID);
        bool GetSeatAcceptanceCAPRoundWise(Int64 PID, Int32 CAPRound);
        bool GETBlockCandidateList(Int64 PID);        
        DataSet getMVSubDiscrepancy(Int32 DID);
        DataSet getNotRecommendedForApprovalCandidate(Int64 InstCode);
        DataSet getNotRecommendedAndRecommendedForApprovalCandidateList(Int64 PID);
        bool SaveARAPenaltyStatus(Int32 InstCD, string Penalty, string CreatedBy, string CreatedIPAddress);
        DataSet CheckARAPenaltyStatus(Int32 InstCode);
        DataSet CandidateApprovalReport(Int64 InstCode);
        Int16 getRORegionID(string RName);
        string getChoiceCodeDisplayByChoiceCode(Int64 ChoiceCode);

    }
}
